### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/CorrR#5]
Hello,

Thank you for the effort you put into making the proposal. I just have one suggestion/recommendation below,
- It will be better to specify how the functions will handle missing values (removing rows, substituting by averages,...)
Thanks!

**Comment by mru4913** [comment]
@hsmohammed 
Thank you for the feedback.
We will update our proposal based on your feedback.

**Comment by K3ra-y** [comment]
Thank you @hsmohammed for the feedback!

The issue is addressed here: 0737227cb3aba77edc32601e65548bedd2797f85 
Same issue is also addressed [for CorrPy](https://github.com/UBC-MDS/CorrPy/commit/de23d35e754587b9e205455e3ca55bce5dada258).
